/*
## Summary
Prepares a core list of Australian Higher Education Providers.

## Description
Given a list of Higher Education Providers, provided by ERA 2018, the ROR codes were added by searching at [https://ror.org/]()
Two tables are created:
- heps_auto: this is a filter of the ror table, to keep only institutions primarily of 'Education' type and in Australia.
- heps: this is a manually provided list (from the ERA 2018 documentation) and is smaller than heps_auto.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
table raw_heps
table core_rors

## Creates
table core_heps
table core_heps_auto

## Data
{
  "https://ror.org/04cxm4j25" : "Australian Catholic University",
  "https://ror.org/019wvm592" : "The Australian National University",
  "https://ror.org/03n0gvg35" : "Batchelor Institute of Indigenous Tertiary Education",
  "https://ror.org/006jxzx88" : "Bond University",
  "https://ror.org/023q4bk22" : "Central Queensland University",
  "https://ror.org/048zcaj52" : "Charles Darwin University",
  "https://ror.org/00wfvh315" : "Charles Sturt University",
  "https://ror.org/02n415q13" : "Curtin University",
  "https://ror.org/02czsnj07" : "Deakin University",
  "https://ror.org/05jhnwe22" : "Edith Cowan University",
  "https://ror.org/05qbzwv83" : "Federation University",
  "https://ror.org/01kpzv902" : "Flinders University",
  "https://ror.org/02sc3r913" : "Griffith University",
  "https://ror.org/04gsp2c11" : "James Cook University",
  "https://ror.org/01rxfrp27" : "La Trobe University",
  "https://ror.org/01sf06y89" : "Macquarie University",
  "https://ror.org/02bfwt286" : "Monash University",
  "https://ror.org/00r4sry34" : "Murdoch University",
  "https://ror.org/03pnv4752" : "Queensland University of Technology",
  "https://ror.org/04ttjf776" : "Royal Melbourne Institute of Technology",
  "https://ror.org/001xkv632" : "Southern Cross University",
  "https://ror.org/031rekg67" : "Swinburne University of Technology",
  "https://ror.org/0351xae06" : "Torrens University Australia",
  "https://ror.org/03r8z3t63" : "University of New South Wales",
  "https://ror.org/00892tw58" : "University of Adelaide",
  "https://ror.org/04s1nv328" : "University of Canberra",
  "https://ror.org/02xn8bh65" : "University of Divinity",
  "https://ror.org/01ej9dk98" : "University of Melbourne",
  "https://ror.org/04r659a56" : "University of New England",
  "https://ror.org/00eae9z71" : "University of Newcastle",
  "https://ror.org/02stey378" : "University of Notre Dame Australia",
  "https://ror.org/00rqy9422" : "University of Queensland",
  "https://ror.org/01p93h210" : "University of South Australia",
  "https://ror.org/04sjbnx57" : "University of Southern Queensland",
  "https://ror.org/0384j8v12" : "University of Sydney",
  "https://ror.org/01nfmeh72" : "University of Tasmania",
  "https://ror.org/03f0f6041" : "University of Technology, Sydney",
  "https://ror.org/047272k79" : "University of Western Australia",
  "https://ror.org/00jtmb277" : "University of Wollongong",
  "https://ror.org/016gb9e15" : "University of the Sunshine Coast",
  "https://ror.org/04j757h98" : "Victoria University",
  "https://ror.org/03t52dk35" : "Western Sydney University"
}

*/
const compile = ({
  ns_core = 'project.dataset',
  replace = false,
}) => `
-- generated by: ${require('path').basename(__filename)}
BEGIN 
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_core}.core_heps\` AS (
    SELECT 
      A.ror,
      B.name,
      A.name AS era_name
    FROM \`${ns_core}.raw_heps\` AS A
    LEFT JOIN \`${ns_core}.core_rors\` AS B ON A.ror = B.ror
    ORDER BY era_name
  );
  ALTER TABLE \`${ns_core}.core_heps\` SET OPTIONS(description='Australian higher education providers (list provided by ERA 2018)');
  ALTER TABLE ${ns_core}.core_heps
  ALTER COLUMN ror  SET OPTIONS (description="Institutional Research Organisations Registry code (see https://ror.org"),
  ALTER COLUMN name SET OPTIONS (description="Name of the Australian higher education provider");

  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_core}.core_heps_auto\` AS (
    SELECT 
      ror,
      name,
    FROM ${ns_core}.core_rors
    WHERE 
      country = 'Australia' AND 
      type_0  = 'Education' AND 
      status  = 'active' 
    ORDER BY name
  );
  ALTER TABLE \`${ns_core}.core_heps_auto\` SET OPTIONS(description='Australian education providers (filtered by country and activity type)');
  ALTER TABLE ${ns_core}.core_heps_auto
  ALTER COLUMN ror  SET OPTIONS (description="Institutional Research Organisations Registry code (see https://ror.org"),
  ALTER COLUMN name SET OPTIONS (description="Name of the Australian education provider");

  -- tests
  SELECT
    'there should be no nulls or empty strings' AS description,
    IF(COUNTIF(ror  IS NULL OR ror  = '') = 0, 'pass', 'fail') AS test1,
    IF(COUNTIF(name IS NULL OR name = '') = 0, 'pass', 'fail') AS test2,
  FROM ${ns_core}.core_heps;
  SELECT
    'there should be no nulls or empty strings' AS description,
    IF(COUNTIF(ror  IS NULL OR ror  = '') = 0, 'pass', 'fail') AS test1,
    IF(COUNTIF(name IS NULL OR name = '') = 0, 'pass', 'fail') AS test2,
  FROM ${ns_core}.core_heps_auto;

END;
`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
