/*
## Summary
Prepares a core list of unique topic codes (eg, ANZSRC FoR codes).

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
table raw_forcodes

## Creates
table core_fors

*/
const app = require('app');
const compile = ({
  ns_core = 'project.dataset',
  replace = false,
}) => `
-- generated by: ${__filename}
BEGIN 
  -- ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_core}.core_fors\` AS (
  --   SELECT '2008' as vers, LENGTH(code) AS len, code, name FROM \`${ns_core}.raw_forcodes_2008\` WHERE LENGTH(code) <= 4 UNION ALL
  --   SELECT '2020' as vers, LENGTH(code) AS len, code, name FROM \`${ns_core}.raw_forcodes_2020\` WHERE LENGTH(code) <= 4 UNION ALL
  --   ORDER BY vers,len,code,name
  -- );
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_core}.core_fors\` AS (
    SELECT 
      vers, 
      LENGTH(code) AS len, 
      code, 
      name 
    FROM \`${ns_core}.raw_forcodes\` 
    WHERE LENGTH(code) <= 4 AND vers = '2020'
    ORDER BY vers,len,code,name
  );
  ALTER TABLE \`${ns_core}.core_fors\` SET OPTIONS(description='Field of Research codes, defined by ANZSRC');
  ALTER TABLE ${ns_core}.core_fors
  ALTER COLUMN vers SET OPTIONS (description="The version of ANZSRC subject classification codes being used (either 2008 or 2020). See: https://www.abs.gov.au/statistics/classifications/"),
  ALTER COLUMN code SET OPTIONS (description="Field of Research (FoR) subject short-code. Either a zero-padded 2,4 or 6 digit number, or 'MD' for multidisciplinary"),
  ALTER COLUMN name SET OPTIONS (description="Field of Research (FoR) subject title");

  -- tests
  SELECT 
    'there should be no intersection between the code sets' AS description,
    IF(COUNTIF(c != 1) = 0, 'pass', 'fail') AS test 
  FROM (SELECT COUNT(1) AS c FROM \`${ns_core}.core_fors\` GROUP BY code);
  SELECT
    'there should be no nulls or empty strings' AS description,
    IF(COUNT(1) = COUNTIF(vers='2008') + COUNTIF(vers='2020'), 'pass', 'fail') AS test1, 
    IF(COUNTIF(code IS NULL OR code = '') = 0                , 'pass', 'fail') AS test2,
    IF(COUNTIF(name IS NULL OR name = '') = 0                , 'pass', 'fail') AS test3,
    IF(COUNTIF(vers != '2008' AND vers != '2020') = 0        , 'pass', 'fail') AS test4
  FROM ${ns_core}.core_fors;
END;
`;
const compile_all = () => [ compile(app.conf()) ];
module.exports = { compile, compile_all };

if (require.main === module) compile_all().forEach(sql => console.log(sql));
