/*
## Summary
Compiles data for the ERA pubishing profile indicator.

## Description
For methodology see:
https://github.com/Curtin-Open-Knowledge-Initiative/for_benchmark_predictions/blob/main/docs/era_2018.md#indicator-research-outputs

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
table research_outputs_base

## Creates
table publishing_profile_*
*/
const app = require('app');
const compile = ({
  ns_core = 'project.dataset',
  scope   = 'world',
  digits  = 4,
  journal = true,
  field   = true,
  year    = true,
  replace = false,
}) => {
let group = [journal ? 'journal' : '', field ? 'field' : '', year ? 'year' : ''].filter(v=>v);
let table = `${ns_core}.publishing_profile_${scope}_${digits}_${group.join('_')}`;
return `
-- generated by: ${__filename}
BEGIN
  -- create publishing profile table ${scope} ${digits}digit (${group})
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} ${table} AS (
    SELECT 
      ${group.join(',')},
      COUNT(1)  AS sum_papers,
      SUM(cits) AS sum_citations,
      SUM(frac) AS sum_portions,
      AVG(cits) AS avg_citations,
      NTILE(100) OVER (PARTITION BY field,year ORDER BY COUNT(1)  DESC) AS cent_papers,
      NTILE(100) OVER (PARTITION BY field,year ORDER BY SUM(cits) DESC) AS cent_citations,
      NTILE(100) OVER (PARTITION BY field,year ORDER BY SUM(frac) DESC) AS cent_portions,
      NTILE(100) OVER (PARTITION BY field,year ORDER BY AVG(cits) DESC) AS cent_cpp,
      RANK()     OVER (PARTITION BY field,year ORDER BY COUNT(1)  DESC) AS rank_papers,
      RANK()     OVER (PARTITION BY field,year ORDER BY SUM(cits) DESC) AS rank_citations,
      RANK()     OVER (PARTITION BY field,year ORDER BY SUM(frac) DESC) AS rank_portions,
      RANK()     OVER (PARTITION BY field,year ORDER BY AVG(cits) DESC) AS rank_cpp
    FROM (
      SELECT 
        ${journal ? 'journal' : 'null'} AS journal,
        ${field   ? 'field'   : 'null'} AS field,
        ${year    ? 'year'    : 'null'} AS year, 
        ANY_VALUE(frac) AS frac, 
        ANY_VALUE(cits) AS cits
      FROM ${ns_core}.research_outputs_world_base
      WHERE LENGTH(field) >= ${digits} ${scope == 'local' ? 'AND is_hep' : ''}
      --WHERE LENGTH(field) >= ${digits}
      GROUP BY paper,journal,field,year
    )
    -- this works because of the ternary operations in the internal select
    GROUP BY journal,field,year
    ORDER BY journal,field,year
  );

  -- sanity checks
  SELECT 'test', COUNT(1) AS total, ${group.map(g => `COUNT(DISTINCT ${g}) AS num_${g}s`).join(',')} FROM ${table};
END;
`;}
const compile_all = () => {
  const sqls = [];
  ['world','local'].forEach(scope => 
    [4,2].forEach(digits => {
      sqls.push(compile({ ...app.conf(), scope, digits, journal: true, field: true, year: true }));
      sqls.push(compile({ ...app.conf(), scope, digits, journal: true, field: true, year:false }));
      sqls.push(compile({ ...app.conf(), scope, digits, journal: true, field:false, year: true }));
      sqls.push(compile({ ...app.conf(), scope, digits, journal:false, field: true, year: true }));
      sqls.push(compile({ ...app.conf(), scope, digits, journal: true, field:false, year:false }));
      sqls.push(compile({ ...app.conf(), scope, digits, journal:false, field: true, year:false }));
      sqls.push(compile({ ...app.conf(), scope, digits, journal:false, field:false, year: true }));
    })
  );
  return sqls;
}
module.exports = { compile, compile_all };

if (require.main === module) compile_all().forEach(sql => console.log(sql));
