/*
## Summary
Ping the DB with a simple query

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0
*/
const app = require('app');
const compile = () => `
-- generated by: ${__filename}
SELECT DISTINCT catalog_name FROM INFORMATION_SCHEMA.SCHEMATA;
`;
const compile_all = () => [ compile(app.conf()) ];
module.exports = { compile, compile_all };

if (require.main === module) compile_all().forEach(sql => console.log(sql));
