/*
## Summary
Ping the DB with a simple query

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0
*/
const compile = () => `
-- generated by: ${require('path').basename(__filename)}
SELECT DISTINCT catalog_name FROM INFORMATION_SCHEMA.SCHEMATA;
`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
