/*
## Summary
Imports raw data from GCS into the journals table.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Creates
table raw_journals
*/
const app = require('app');
const compile = ({
  ns_core = 'project.dataset',
  bucket  = 'gs://rt-era-public',
}) => `
-- generated by: ${__filename}
BEGIN
  CREATE OR REPLACE TABLE \`${ns_core}.raw_journals_2018\` (
    era_id        STRING NOT NULL  OPTIONS(description='A unique identifier assigned by the ARC'),
    title         STRING NOT NULL  OPTIONS(description='Journal title (English)'),
    foreign_title STRING NOT NULL  OPTIONS(description='Journal title (non-English) for foreign journals'),
    issns         ARRAY<STRING>    OPTIONS(description='List of ISSNs for the journal'),
    forcodes      ARRAY<STRUCT< 
      code        STRING NOT NULL  OPTIONS(description='FoR code (a string because the values are zero padded and can be "MD")'),
      name        STRING NOT NULL  OPTIONS(description='FoR name')
    >>                             OPTIONS(description='Field of Research (FoR) codes assigned by ARC to the journal'),
    weighted      ARRAY<STRUCT<
      code        STRING  NOT NULL OPTIONS(description='FoR code (a string because the values are zero padded and can be "MD")'),
      weight      INTEGER NOT NULL OPTIONS(description='Portional assignment of this FoR code')
    >>                             OPTIONS(description='Field of Research (FoR) codes assigned by ARC to the journal.'),
  )                                OPTIONS(description='Official ERA 2023 Journal List');
  TRUNCATE TABLE \`${ns_core}.raw_journals_2018\`;
  LOAD DATA INTO \`${ns_core}.raw_journals_2018\` FROM FILES (
    format = 'JSON',
    uris = ['${bucket}/data/raw/raw_journals_2018/data.jsonl']
  );

  CREATE OR REPLACE TABLE \`${ns_core}.raw_journals_2023\` (
    era_id        STRING NOT NULL  OPTIONS(description='A unique identifier assigned by the ARC'),
    title         STRING NOT NULL  OPTIONS(description='Journal title (English)'),
    foreign_title STRING NOT NULL  OPTIONS(description='Journal title (non-English) for foreign journals'),
    issns         ARRAY<STRING>    OPTIONS(description='List of ISSNs for the journal'),
    forcodes      ARRAY<STRUCT< 
      code        STRING NOT NULL  OPTIONS(description='FoR code (a string because the values are zero padded and can be "MD")'),
      name        STRING NOT NULL  OPTIONS(description='FoR name')
    >>                             OPTIONS(description='Field of Research (FoR) codes assigned by ARC to the journal'),
    weighted      ARRAY<STRUCT<
      code        STRING  NOT NULL OPTIONS(description='FoR code (a string because the values are zero padded and can be "MD")'),
      weight      INTEGER NOT NULL OPTIONS(description='Portional assignment of this FoR code')
    >>                             OPTIONS(description='Field of Research (FoR) codes assigned by ARC to the journal.'),
  )                                OPTIONS(description='Official ERA 2023 Journal List');
  TRUNCATE TABLE \`${ns_core}.raw_journals_2023\`;
  LOAD DATA INTO \`${ns_core}.raw_journals_2023\` FROM FILES (
    format = 'JSON',
    uris = ['${bucket}/data/raw/raw_journals_2023/data.jsonl']
  );
END;
`;
const compile_all = () => [ compile(app.conf()) ];
module.exports = { compile, compile_all };

if (require.main === module) compile_all().forEach(sql => console.log(sql));
