/*
## Summary
Imports raw data from GCS into the ISSNs table.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
file coki.cloud

## Creates
table raw_issns
*/
const compile = ({
  ns_core = 'project.dataset',
  bucket  = 'gs://rt-era-public',
}) => `
-- generated by: ${require('path').basename(__filename)}
BEGIN
  CREATE OR REPLACE TABLE \`${ns_core}.raw_issns\` (
    issn  STRING NOT NULL OPTIONS(description='ISSN'),
    issnl STRING NOT NULL OPTIONS(description='Linking ISSN'),
  )                       OPTIONS(description='Official ISSN -> ISSN-L mapping from https://www.issn.org/wp-content/uploads/2014/03/issnltables.zip');
  TRUNCATE TABLE \`${ns_core}.raw_issns\`;
  LOAD DATA INTO \`${ns_core}.raw_issns\` FROM FILES (
    format = 'JSON',
    uris = ['${bucket}/data/raw/raw_issns/data.jsonl']
  );
END;
`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
