/*
## Summary
Imports raw data from GCS into the institutions (ROR) table.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
file coki.cloud

## Creates
table raw_rors
*/
const compile = ({
  ns_core = 'project.dataset',
  bucket  = 'gs://rt-era-public',
}) => `
-- generated by: ${__filename}
BEGIN
  CREATE OR REPLACE TABLE \`${ns_core}.raw_rors\` (
    ror     STRING        OPTIONS(description='Research Organisation Registry unique identifier'),
    since   STRING        OPTIONS(description='The year that the institution was established'),
    status  STRING        OPTIONS(description='Current status of the institution (filter for active)'),
    type_0  STRING        OPTIONS(description='Primary activity type (ie, types[0])'),
    country STRING        OPTIONS(description='Country in which the research institution is located'),
    name    STRING        OPTIONS(description='Name of the research institution'),
    link_0  STRING        OPTIONS(description='Primary URL (ie, links[0])'),
    types   ARRAY<STRING> OPTIONS(description='All activity types that the institution is engaged in'),
    links   ARRAY<STRING> OPTIONS(description='All links associated with the institution'),
  )                       OPTIONS(description='Official Research Organisation Registry data sourced from https://ror.readme.io/docs/data-dump');
  TRUNCATE TABLE \`${ns_core}.raw_rors\`;
  LOAD DATA INTO \`${ns_core}.raw_rors\` FROM FILES (
    format = 'JSON',
    uris = ['${bucket}/data/raw/raw_rors/data.jsonl']
  );  
END;
`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
