/*
## Summary
Imports raw data from GCS into the topics (FoR) table.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
file coki.cloud

## Creates
table raw_forcodes

*/
const compile = ({
  ns_core = 'project.dataset',
  bucket  = 'gs://rt-era-public',
}) => `
-- generated by: ${require('path').basename(__filename)}
BEGIN
  CREATE OR REPLACE TABLE \`${ns_core}.raw_forcodes\` (
    vers STRING OPTIONS(description='ANZSIC version, either 2008 or 2020'),
    code STRING OPTIONS(description='Field of research code (either 2-digit, 4-digit or 6-digit)'),
    name STRING OPTIONS(description='Field of research'),
  )             OPTIONS(description='Official Field of Research (FoR) codes sourced from Official Research Organisation Registry data sourced from http://aria.stats.govt.nz/ and https://www.abs.gov.au/');
  TRUNCATE TABLE \`${ns_core}.raw_forcodes\`;
  LOAD DATA INTO \`${ns_core}.raw_forcodes\` FROM FILES (
    format = 'JSON',
    uris = ['${bucket}/data/raw/raw_forcodes/data.jsonl']
  );
END;
`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
