/*
## Summary
Create report tables for a single institution (default: Curtin University).

## Description
The generated tables are flat in structure, so that they can be downloaded as CSVs.
Curtin university is identified by the RoR code: https://ror.org/02n415q13

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
table raw_papers
table core_papers
table core_journals
table core_fors
table research_outputs_*
table benchmarks_summary_*

## Creates
table inst_papers
table inst_outputs
table inst_summary_by_field_year
table inst_summary_by_field
table inst_summary_by_year
table inst_paper_classes
table inst_class_tallies_by_field_year
table inst_class_tallies_by_field
table inst_class_tallies_by_year
*/
const compile = ({
  ns_core   = 'project.dataset',
  ns_inst   = 'project.dataset',
  inst_code = 'https://ror.org/02n415q13',
  digits    = 4,
  replace   = false,
}) => `
-- generated by: ${__filename}
BEGIN

  CREATE SCHEMA IF NOT EXISTS \`${ns_inst}\` OPTIONS (
    description = 'single institution analysis for inst'
  );

  --
  -- Using the era core_papers table, build a list of journal outputs
  --
  -- Institutionally affiliated publications, drawn directly from the pre-determined core_papers
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_papers\` AS (
    SELECT 
      A.doi             AS paper_doi,
      --A.title           AS paper_title,
      A.era_id          AS journal_era_id, 
      B.title           AS journal_title,
      A.year_published  AS year, 
      A.num_citations   AS citations, 
      --A.authors         AS authors,
      A.fors            AS field
    -- limited to whatever restrictions built the core table (eg ERA date range)
    FROM \`${ns_core}.core_papers\` AS A
    LEFT JOIN UNNEST(rors) AS ror
    -- add journal title
    LEFT JOIN \`${ns_core}.core_journals\` AS B ON A.era_id = B.era_id
    -- restrict to the single institution
    WHERE ror = '${inst_code}' -- inst 
    -- AND B.era_round = '2023'
    ORDER BY year
  );
  ALTER TABLE \`${ns_inst}.inst_papers\` SET OPTIONS(description='inst outputs that meet the basic criteria for ERA analysis');
  ALTER TABLE ${ns_inst}.inst_papers
  ALTER COLUMN paper_doi      SET OPTIONS (description="Digitial Object Identifier of the paper"),
  --ALTER COLUMN paper_title    SET OPTIONS (description="Title of the paper"),
  ALTER COLUMN journal_era_id SET OPTIONS (description="ERA Journal List ID of the encompassing journal"),
  ALTER COLUMN journal_title  SET OPTIONS (description="Journal Title (from the ERA Journal List)"),
  ALTER COLUMN year           SET OPTIONS (description="Year of publication"),
  ALTER COLUMN citations      SET OPTIONS (description="Current number of citations"),
  --ALTER COLUMN authors        SET OPTIONS (description="List of authors from Crossref"),
  ALTER COLUMN field          SET OPTIONS (description="ANZSIC field of research codes inherited from the journal");

  -- 
  -- Using the DOI table, filter for all inst outputs (based on RoR code) over all time. Two flag columns indicate if the output is in an ERA journal or is a journal article
  --
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_outputs\` AS (
    WITH
    -- extract a list of papers that link to inst (via RoR)
    linked_by_ror AS (
      SELECT doi
      FROM \`${ns_core}.raw_papers\` --TABLESAMPLE SYSTEM (0.01 PERCENT) 
      LEFT JOIN UNNEST(rors) AS ror
      WHERE ror = '${inst_code}' -- inst
      GROUP BY doi
    ),
    -- extract a list of papers that link to an ERA journal
    linked_by_era AS (
      SELECT doi
      FROM \`${ns_core}.raw_papers\` --TABLESAMPLE SYSTEM (0.01 PERCENT) 
      LEFT JOIN UNNEST(issns) AS issn
      INNER JOIN (    -- note: subject to constraints on the journal list (eg ERA 2018 vs 2023)
        SELECT issn
        FROM ${ns_core}.core_journals
        LEFT JOIN UNNEST(issns) AS issn
      ) AS B
      ON issn = B.issn
      GROUP BY doi
    )
    SELECT 
      A.doi                      AS doi,
      A.type = 'journal-article' AS is_article,
      C.doi IS NOT NULL          AS in_era,
      A.year                     AS year, 
      A.cits                     AS citations, 
      --A.title                           AS title,
      --A.authors                         AS authors
    FROM \`${ns_core}.raw_papers\` AS A
    INNER JOIN linked_by_ror AS B ON A.doi = B.doi
    LEFT  JOIN linked_by_era AS C ON A.doi = C.doi
    ORDER BY year DESC, citations DESC
  );
  ALTER TABLE \`${ns_inst}.inst_outputs\` SET OPTIONS(description='inst outputs that meet the basic criteria for ERA analysis');
  ALTER TABLE ${ns_inst}.inst_outputs
  ALTER COLUMN doi        SET OPTIONS (description="Digitial Object Identifier of the paper"),
  ALTER COLUMN is_article SET OPTIONS (description="True if the output is listed as a journal article in the COKI dataset"),
  ALTER COLUMN in_era     SET OPTIONS (description="True if the output has been linked to a journal in the ERA Journal List"),
  ALTER COLUMN year       SET OPTIONS (description="Year of publication"),
  ALTER COLUMN citations  SET OPTIONS (description="Current number of citations");
  --ALTER COLUMN title      SET OPTIONS (description="Title of the research output"),
  --ALTER COLUMN authors    SET OPTIONS (description="List of authors from Crossref");
  SELECT 
    COUNT(1)                           AS outputs,
    COUNTIF(is_article)                AS articles,
    COUNTIF(in_era)                    AS outputs_in_era,
    COUNTIF(is_article AND in_era)     AS articles_in_era,
    COUNTIF(NOT in_era)                AS outputs_missed_by_era,
    COUNTIF(is_article AND NOT in_era) AS articles_missed_by_era
  FROM ${ns_inst}.inst_outputs;

  --
  -- Build tables that summarises outputs for inst
  --
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_summary_by_field_year\` AS (
    WITH
    A AS (SELECT * FROM \`${ns_core}.research_outputs_local_${digits}_institution_field_year\` WHERE institution = '${inst_code}'),
    B AS (SELECT * FROM \`${ns_core}.research_outputs_world_${digits}_institution_field_year\` WHERE institution = '${inst_code}'),
    C AS (SELECT code,name FROM ${ns_core}.core_fors)
    SELECT 
      A.field,
      C.name,
      A.year,

       A.sum_papers AS papers,
      A.rank_papers AS papers_rank_local,
      B.rank_papers AS papers_rank_world,
      B.cent_papers AS papers_cent_world,

       A.sum_citations AS citations,
      A.rank_citations AS citations_rank_local,
      B.rank_citations AS citations_rank_world,
      B.cent_citations AS citations_cent_world,

       A.sum_portions AS portions,
      A.rank_portions AS portions_rank_local,
      B.rank_portions AS portions_rank_world,
      B.cent_portions AS portions_cent_world,

      A.avg_citations AS cpp,
      A.rank_cpp      AS cpp_rank_local,
      B.rank_cpp      AS cpp_rank_world,
      B.cent_cpp      AS cpp_cent_world,
    FROM A 
    LEFT JOIN B ON A.field = B.field AND A.year = B.year
    LEFT JOIN C ON A.field = C.code
    ORDER BY field,year
  );
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_summary_by_field\` AS (
    WITH
    A AS (SELECT * FROM \`${ns_core}.research_outputs_local_${digits}_institution_field\` WHERE institution = '${inst_code}'),
    B AS (SELECT * FROM \`${ns_core}.research_outputs_world_${digits}_institution_field\` WHERE institution = '${inst_code}'),
    C AS (SELECT code,name FROM ${ns_core}.core_fors)
    SELECT 
      A.field,
      C.name,

       A.sum_papers AS papers,
      A.rank_papers AS papers_rank_local,
      B.rank_papers AS papers_rank_world,
      B.cent_papers AS papers_cent_world,

       A.sum_citations AS citations,
      A.rank_citations AS citations_rank_local,
      B.rank_citations AS citations_rank_world,
      B.cent_citations AS citations_cent_world,

       A.sum_portions AS portions,
      A.rank_portions AS portions_rank_local,
      B.rank_portions AS portions_rank_world,
      B.cent_portions AS portions_cent_world,

      A.avg_citations AS cpp,
      A.rank_cpp      AS cpp_rank_local,
      B.rank_cpp      AS cpp_rank_world,
      B.cent_cpp      AS cpp_cent_world,
    FROM A 
    LEFT JOIN B ON A.field = B.field
    LEFT JOIN C ON A.field = C.code
    ORDER BY field
  );
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_summary_by_year\` AS (
    WITH
    A AS (SELECT * FROM \`${ns_core}.research_outputs_local_${digits}_institution_year\` WHERE institution = '${inst_code}'),
    B AS (SELECT * FROM \`${ns_core}.research_outputs_world_${digits}_institution_year\` WHERE institution = '${inst_code}')
    SELECT 
      A.year,

       A.sum_papers AS papers,
      A.rank_papers AS papers_rank_local,
      B.rank_papers AS papers_rank_world,
      B.cent_papers AS papers_cent_world,

       A.sum_citations AS citations,
      A.rank_citations AS citations_rank_local,
      B.rank_citations AS citations_rank_world,
      B.cent_citations AS citations_cent_world,

       A.sum_portions AS portions,
      A.rank_portions AS portions_rank_local,
      B.rank_portions AS portions_rank_world,
      B.cent_portions AS portions_cent_world,

      A.avg_citations AS cpp,
      A.rank_cpp      AS cpp_rank_local,
      B.rank_cpp      AS cpp_rank_world,
      B.cent_cpp      AS cpp_cent_world,
    FROM A 
    LEFT JOIN B ON A.year = B.year
    ORDER BY year
  );
  ALTER TABLE \`${ns_inst}.inst_summary_by_field_year\` SET OPTIONS(description='Total inst outputs by field of research and year');
  ALTER TABLE ${ns_inst}.inst_summary_by_field_year
  ALTER COLUMN field     SET OPTIONS (description="ANZSIC field of research code"),
  ALTER COLUMN name      SET OPTIONS(description='ANZSIC field of research name'),
  ALTER COLUMN year      SET OPTIONS (description="analysis year (publication year of articles)"),
  ALTER COLUMN papers    SET OPTIONS (description="total number of papers published by inst staff"),
  ALTER COLUMN citations SET OPTIONS (description="total number of citations for all papers"),
  ALTER COLUMN portions  SET OPTIONS (description="sum of paper apportionments to this field of research"),
  ALTER COLUMN cpp       SET OPTIONS (description="average citations per paper"),
  ALTER COLUMN papers_rank_local    SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN papers_rank_world    SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN papers_cent_world    SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN citations_rank_local SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN citations_rank_world SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN citations_cent_world SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN portions_rank_local  SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN portions_rank_world  SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN portions_cent_world  SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN cpp_rank_local       SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN cpp_rank_world       SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN cpp_cent_world       SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world");

  ALTER TABLE \`${ns_inst}.inst_summary_by_field\` SET OPTIONS(description='Total inst outputs by field of research');
  ALTER TABLE ${ns_inst}.inst_summary_by_field
  ALTER COLUMN field     SET OPTIONS (description="ANZSIC field of research code"),
  ALTER COLUMN name      SET OPTIONS(description='ANZSIC field of research name'),
  ALTER COLUMN papers    SET OPTIONS (description="total number of papers published by inst staff"),
  ALTER COLUMN citations SET OPTIONS (description="total number of citations for all papers"),
  ALTER COLUMN portions  SET OPTIONS (description="sum of paper apportionments to this field of research"),
  ALTER COLUMN cpp       SET OPTIONS (description="average citations per paper"),
  ALTER COLUMN papers_rank_local    SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN papers_rank_world    SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN papers_cent_world    SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN citations_rank_local SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN citations_rank_world SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN citations_cent_world SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN portions_rank_local  SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN portions_rank_world  SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN portions_cent_world  SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN cpp_rank_local       SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN cpp_rank_world       SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN cpp_cent_world       SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world");

  ALTER TABLE \`${ns_inst}.inst_summary_by_year\` SET OPTIONS(description='Total inst outputs by year');
  ALTER TABLE ${ns_inst}.inst_summary_by_year
  ALTER COLUMN year      SET OPTIONS (description="analysis year (publication year of articles)"),
  ALTER COLUMN papers    SET OPTIONS (description="total number of papers published by inst staff"),
  ALTER COLUMN citations SET OPTIONS (description="total number of citations for all papers"),
  ALTER COLUMN portions  SET OPTIONS (description="sum of paper apportionments to this field of research"),
  ALTER COLUMN cpp       SET OPTIONS (description="average citations per paper"),
  ALTER COLUMN papers_rank_local    SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN papers_rank_world    SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN papers_cent_world    SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN citations_rank_local SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN citations_rank_world SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN citations_cent_world SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN portions_rank_local  SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN portions_rank_world  SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN portions_cent_world  SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world"),
  ALTER COLUMN cpp_rank_local       SET OPTIONS (description="rank versus other Australian HEPs (1:best, 40:worst)"),
  ALTER COLUMN cpp_rank_world       SET OPTIONS (description="rank versus all world instutions (1:best)"),
  ALTER COLUMN cpp_cent_world       SET OPTIONS (description="world percentile, 1-100. 1 = top 1% in the world");

  -- Assigns RCI classes to inst outputs
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_paper_classes\` AS (
    SELECT DISTINCT
      paper_doi AS doi,
      A.year,
      citations,
      F.code,
      G.name,
      IF (B.cpp_local = 0, 0.0, ROUND(citations / B.cpp_local,4)) AS rci_local,
      IF (B.cpp_world = 0, 0.0, ROUND(citations / B.cpp_world,4)) AS rci_world,
      IF (B.cpp_hpi   = 0, 0.0, ROUND(citations / B.cpp_hpi  ,4)) AS rci_hpi,
      citations > B.cpp_hpi AS high_perf,
      CASE
        WHEN citations > B.ctile_01 THEN 1
        WHEN citations > B.ctile_05 THEN 5
        WHEN citations > B.ctile_10 THEN 10
        WHEN citations > B.ctile_25 THEN 25
        WHEN citations > B.ctile_50 THEN 50
        ELSE 100
      END AS cent_group,
      CASE
        WHEN citations > B.dynamic_c4 THEN 5
        WHEN citations > B.dynamic_c3 THEN 4
        WHEN citations > B.dynamic_c2 THEN 3
        WHEN citations > B.dynamic_c1 THEN 2
        WHEN citations > B.dynamic_c0 THEN 1
        ELSE 0
      END AS cat_dynamic,
      CASE
        WHEN citations > B.static_c5 THEN 6
        WHEN citations > B.static_c4 THEN 5
        WHEN citations > B.static_c3 THEN 4
        WHEN citations > B.static_c2 THEN 3
        WHEN citations > B.static_c1 THEN 2
        WHEN citations > B.static_c0 THEN 1
        ELSE 0
      END AS cat_static
    FROM \`${ns_inst}.inst_papers\` AS A
    LEFT JOIN UNNEST(field) as F
    LEFT JOIN \`${ns_core}.benchmarks_summary_4\` AS B ON A.year = B.year AND F.code = B.field
    LEFT JOIN \`${ns_core}.core_fors\` AS G ON F.code = G.code
    WHERE LENGTH(F.code) = 4
    ORDER BY year, doi, code
  );
  ALTER TABLE \`${ns_inst}.inst_paper_classes\` SET OPTIONS(description='inst papers with various ERA ratings methods');
  ALTER TABLE ${ns_inst}.inst_paper_classes
  ALTER COLUMN doi         SET OPTIONS(description="digital object identifier for the paper"),
  ALTER COLUMN year        SET OPTIONS(description="year of publication"),
  ALTER COLUMN citations   SET OPTIONS(description="number of citations"),
  ALTER COLUMN code        SET OPTIONS(description="ANZSIC field of research code"),
  ALTER COLUMN name        SET OPTIONS(description='ANZSIC field of research name'),
  ALTER COLUMN rci_local   SET OPTIONS(description="relative citation impact using the Australian benchmark"),
  ALTER COLUMN rci_world   SET OPTIONS(description="relative citation impact using the world benchmark"),
  ALTER COLUMN rci_hpi     SET OPTIONS(description="relative citation impact using the world high-performing institutions benchmark"),
  ALTER COLUMN high_perf   SET OPTIONS(description="true if the paper is above the high-performing benchmark"),
  ALTER COLUMN cent_group  SET OPTIONS(description="ERA percentile grouping. The groupings are top 1%, 1-5%, 5-10%, 10-25%, 25-50%, bottom 50%"),
  ALTER COLUMN cat_dynamic SET OPTIONS(description="ERA dynamic RCI category. 0:uncited, 5:best"),
  ALTER COLUMN cat_static  SET OPTIONS(description="ERA static RCI category. 0:uncited, 6:best");

  -- tally up RCI classes by (field,year)
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_class_tallies_by_field_year\` AS (
    SELECT
      year,
      code AS field,
      name,
      COUNT(1) AS publications,
      SUM(citations) AS citations,
      ROUND(AVG(rci_local),4) AS avg_rci_local,
      ROUND(AVG(rci_world),4) AS avg_rci_world,
      ROUND(AVG(rci_hpi)  ,4) AS avg_rci_hpi,
      COUNTIF(high_perf) AS high_perf,
      COUNTIF(cent_group =   1) AS c1,
      COUNTIF(cent_group =   5) AS c5,
      COUNTIF(cent_group =  10) AS c10,
      COUNTIF(cent_group =  25) AS c25,
      COUNTIF(cent_group =  50) AS c50,
      COUNTIF(cent_group = 100) AS c100,
      COUNTIF(cat_dynamic = 5) AS d5,
      COUNTIF(cat_dynamic = 4) AS d4,
      COUNTIF(cat_dynamic = 3) AS d3,
      COUNTIF(cat_dynamic = 2) AS d2,
      COUNTIF(cat_dynamic = 1) AS d1,
      COUNTIF(cat_dynamic = 0) AS d0,
      COUNTIF(cat_static = 6) AS s6,
      COUNTIF(cat_static = 5) AS s5,
      COUNTIF(cat_static = 4) AS s4,
      COUNTIF(cat_static = 3) AS s3,
      COUNTIF(cat_static = 2) AS s2,
      COUNTIF(cat_static = 1) AS s1,
      COUNTIF(cat_static = 0) AS s0
    FROM ${ns_inst}.inst_paper_classes
    GROUP BY year,field,name
    ORDER BY year,field,name
  );

  -- tally up RCI classes by (field)
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_class_tallies_by_field\` AS (
    SELECT
      code AS field,
      name,
      COUNT(1) AS publications,
      SUM(citations) AS citations,
      ROUND(AVG(rci_local),4) AS avg_rci_local,
      ROUND(AVG(rci_world),4) AS avg_rci_world,
      ROUND(AVG(rci_hpi)  ,4) AS avg_rci_hpi,
      COUNTIF(high_perf) AS high_perf,
      COUNTIF(cent_group =   1) AS c1,
      COUNTIF(cent_group =   5) AS c5,
      COUNTIF(cent_group =  10) AS c10,
      COUNTIF(cent_group =  25) AS c25,
      COUNTIF(cent_group =  50) AS c50,
      COUNTIF(cent_group = 100) AS c100,
      COUNTIF(cat_dynamic = 5) AS d5,
      COUNTIF(cat_dynamic = 4) AS d4,
      COUNTIF(cat_dynamic = 3) AS d3,
      COUNTIF(cat_dynamic = 2) AS d2,
      COUNTIF(cat_dynamic = 1) AS d1,
      COUNTIF(cat_dynamic = 0) AS d0,
      COUNTIF(cat_static = 6) AS s6,
      COUNTIF(cat_static = 5) AS s5,
      COUNTIF(cat_static = 4) AS s4,
      COUNTIF(cat_static = 3) AS s3,
      COUNTIF(cat_static = 2) AS s2,
      COUNTIF(cat_static = 1) AS s1,
      COUNTIF(cat_static = 0) AS s0
    FROM ${ns_inst}.inst_paper_classes
    GROUP BY field,name
    ORDER BY field,name
  );

  -- tally up RCI classes by (year)
  ${replace ? 'CREATE OR REPLACE TABLE' : 'CREATE TABLE IF NOT EXISTS'} \`${ns_inst}.inst_class_tallies_by_year\` AS (
    SELECT
      year,
      COUNT(1) AS publications,
      SUM(citations) AS citations,
      ROUND(AVG(rci_local),4) AS avg_rci_local,
      ROUND(AVG(rci_world),4) AS avg_rci_world,
      ROUND(AVG(rci_hpi)  ,4) AS avg_rci_hpi,
      COUNTIF(high_perf) AS high_perf,
      COUNTIF(cent_group =   1) AS c1,
      COUNTIF(cent_group =   5) AS c5,
      COUNTIF(cent_group =  10) AS c10,
      COUNTIF(cent_group =  25) AS c25,
      COUNTIF(cent_group =  50) AS c50,
      COUNTIF(cent_group = 100) AS c100,
      COUNTIF(cat_dynamic = 5) AS d5,
      COUNTIF(cat_dynamic = 4) AS d4,
      COUNTIF(cat_dynamic = 3) AS d3,
      COUNTIF(cat_dynamic = 2) AS d2,
      COUNTIF(cat_dynamic = 1) AS d1,
      COUNTIF(cat_dynamic = 0) AS d0,
      COUNTIF(cat_static = 6) AS s6,
      COUNTIF(cat_static = 5) AS s5,
      COUNTIF(cat_static = 4) AS s4,
      COUNTIF(cat_static = 3) AS s3,
      COUNTIF(cat_static = 2) AS s2,
      COUNTIF(cat_static = 1) AS s1,
      COUNTIF(cat_static = 0) AS s0
    FROM ${ns_inst}.inst_paper_classes
    GROUP BY year
    ORDER BY year
  );
  ALTER TABLE \`${ns_inst}.inst_class_tallies_by_field_year\` SET OPTIONS(description='Tallies of inst papers in each citation class, by field of research and year');
  ALTER TABLE ${ns_inst}.inst_class_tallies_by_field_year
  ALTER COLUMN year          SET OPTIONS(description='year of analysis (publication year of papers)'),
  ALTER COLUMN field         SET OPTIONS(description='ANZSIC field of research code'),
  ALTER COLUMN name          SET OPTIONS(description='ANZSIC field of research name'),
  ALTER COLUMN publications  SET OPTIONS(description='total number of publications'),
  ALTER COLUMN citations     SET OPTIONS(description='total number of citations'),
  ALTER COLUMN avg_rci_local SET OPTIONS(description='average RCI-local score'),
  ALTER COLUMN avg_rci_world SET OPTIONS(description='average RCI-world score'),
  ALTER COLUMN avg_rci_hpi   SET OPTIONS(description='average RCI-high-performing score'),
  ALTER COLUMN high_perf     SET OPTIONS(description='number of papers that are above the high performance threshold'),
  ALTER COLUMN c1            SET OPTIONS(description='number of papers in ERA percentile range < 1%'),
  ALTER COLUMN c5            SET OPTIONS(description='number of papers in ERA percentile range 1% to < 5%'),
  ALTER COLUMN c10           SET OPTIONS(description='number of papers in ERA percentile range 5% to < 10%'),
  ALTER COLUMN c25           SET OPTIONS(description='number of papers in ERA percentile range 10% to < 25%'),
  ALTER COLUMN c50           SET OPTIONS(description='number of papers in ERA percentile range 25% to < 50%'),
  ALTER COLUMN c100          SET OPTIONS(description='number of papers in ERA percentile range >= 50%'),
  ALTER COLUMN d5            SET OPTIONS(description='number of papers with dynamic RCI class 5 (best)'),
  ALTER COLUMN d4            SET OPTIONS(description='number of papers with dynamic RCI class 4'),
  ALTER COLUMN d3            SET OPTIONS(description='number of papers with dynamic RCI class 3'),
  ALTER COLUMN d2            SET OPTIONS(description='number of papers with dynamic RCI class 2'),
  ALTER COLUMN d1            SET OPTIONS(description='number of papers with dynamic RCI class 1'),
  ALTER COLUMN d0            SET OPTIONS(description='number of papers with dynamic RCI class 0 (uncited)'),
  ALTER COLUMN s6            SET OPTIONS(description='number of papers with static RCI class 6 (best)'),
  ALTER COLUMN s5            SET OPTIONS(description='number of papers with static RCI class 5'),
  ALTER COLUMN s4            SET OPTIONS(description='number of papers with static RCI class 4'),
  ALTER COLUMN s3            SET OPTIONS(description='number of papers with static RCI class 3'),
  ALTER COLUMN s2            SET OPTIONS(description='number of papers with static RCI class 2'),
  ALTER COLUMN s1            SET OPTIONS(description='number of papers with static RCI class 1'),
  ALTER COLUMN s0            SET OPTIONS(description='number of papers with static RCI class 0 (uncited)');

  ALTER TABLE \`${ns_inst}.inst_class_tallies_by_field\` SET OPTIONS(description='Tallies of inst papers in each citation class, by field of research');
  ALTER TABLE ${ns_inst}.inst_class_tallies_by_field
  ALTER COLUMN field         SET OPTIONS(description='ANZSIC field of research code'),
  ALTER COLUMN name          SET OPTIONS(description='ANZSIC field of research name'),
  ALTER COLUMN publications  SET OPTIONS(description='total number of publications'),
  ALTER COLUMN citations     SET OPTIONS(description='total number of citations'),
  ALTER COLUMN avg_rci_local SET OPTIONS(description='average RCI-local score'),
  ALTER COLUMN avg_rci_world SET OPTIONS(description='average RCI-world score'),
  ALTER COLUMN avg_rci_hpi   SET OPTIONS(description='average RCI-high-performing score'),
  ALTER COLUMN high_perf     SET OPTIONS(description='number of papers that are above the high performance threshold'),
  ALTER COLUMN c1            SET OPTIONS(description='number of papers in ERA percentile range < 1%'),
  ALTER COLUMN c5            SET OPTIONS(description='number of papers in ERA percentile range 1% to < 5%'),
  ALTER COLUMN c10           SET OPTIONS(description='number of papers in ERA percentile range 5% to < 10%'),
  ALTER COLUMN c25           SET OPTIONS(description='number of papers in ERA percentile range 10% to < 25%'),
  ALTER COLUMN c50           SET OPTIONS(description='number of papers in ERA percentile range 25% to < 50%'),
  ALTER COLUMN c100          SET OPTIONS(description='number of papers in ERA percentile range >= 50%'),
  ALTER COLUMN d5            SET OPTIONS(description='number of papers with dynamic RCI class 5 (best)'),
  ALTER COLUMN d4            SET OPTIONS(description='number of papers with dynamic RCI class 4'),
  ALTER COLUMN d3            SET OPTIONS(description='number of papers with dynamic RCI class 3'),
  ALTER COLUMN d2            SET OPTIONS(description='number of papers with dynamic RCI class 2'),
  ALTER COLUMN d1            SET OPTIONS(description='number of papers with dynamic RCI class 1'),
  ALTER COLUMN d0            SET OPTIONS(description='number of papers with dynamic RCI class 0 (uncited)'),
  ALTER COLUMN s6            SET OPTIONS(description='number of papers with static RCI class 6 (best)'),
  ALTER COLUMN s5            SET OPTIONS(description='number of papers with static RCI class 5'),
  ALTER COLUMN s4            SET OPTIONS(description='number of papers with static RCI class 4'),
  ALTER COLUMN s3            SET OPTIONS(description='number of papers with static RCI class 3'),
  ALTER COLUMN s2            SET OPTIONS(description='number of papers with static RCI class 2'),
  ALTER COLUMN s1            SET OPTIONS(description='number of papers with static RCI class 1'),
  ALTER COLUMN s0            SET OPTIONS(description='number of papers with static RCI class 0 (uncited)');

  ALTER TABLE \`${ns_inst}.inst_class_tallies_by_year\` SET OPTIONS(description='Tallies of inst papers in each citation class, by year');
  ALTER TABLE ${ns_inst}.inst_class_tallies_by_year
  ALTER COLUMN year          SET OPTIONS(description='year of analysis (publication year of papers)'),
  ALTER COLUMN publications  SET OPTIONS(description='total number of publications'),
  ALTER COLUMN citations     SET OPTIONS(description='total number of citations'),
  ALTER COLUMN avg_rci_local SET OPTIONS(description='average RCI-local score'),
  ALTER COLUMN avg_rci_world SET OPTIONS(description='average RCI-world score'),
  ALTER COLUMN avg_rci_hpi   SET OPTIONS(description='average RCI-high-performing score'),
  ALTER COLUMN high_perf     SET OPTIONS(description='number of papers that are above the high performance threshold'),
  ALTER COLUMN c1            SET OPTIONS(description='number of papers in ERA percentile range < 1%'),
  ALTER COLUMN c5            SET OPTIONS(description='number of papers in ERA percentile range 1% to < 5%'),
  ALTER COLUMN c10           SET OPTIONS(description='number of papers in ERA percentile range 5% to < 10%'),
  ALTER COLUMN c25           SET OPTIONS(description='number of papers in ERA percentile range 10% to < 25%'),
  ALTER COLUMN c50           SET OPTIONS(description='number of papers in ERA percentile range 25% to < 50%'),
  ALTER COLUMN c100          SET OPTIONS(description='number of papers in ERA percentile range >= 50%'),
  ALTER COLUMN d5            SET OPTIONS(description='number of papers with dynamic RCI class 5 (best)'),
  ALTER COLUMN d4            SET OPTIONS(description='number of papers with dynamic RCI class 4'),
  ALTER COLUMN d3            SET OPTIONS(description='number of papers with dynamic RCI class 3'),
  ALTER COLUMN d2            SET OPTIONS(description='number of papers with dynamic RCI class 2'),
  ALTER COLUMN d1            SET OPTIONS(description='number of papers with dynamic RCI class 1'),
  ALTER COLUMN d0            SET OPTIONS(description='number of papers with dynamic RCI class 0 (uncited)'),
  ALTER COLUMN s6            SET OPTIONS(description='number of papers with static RCI class 6 (best)'),
  ALTER COLUMN s5            SET OPTIONS(description='number of papers with static RCI class 5'),
  ALTER COLUMN s4            SET OPTIONS(description='number of papers with static RCI class 4'),
  ALTER COLUMN s3            SET OPTIONS(description='number of papers with static RCI class 3'),
  ALTER COLUMN s2            SET OPTIONS(description='number of papers with static RCI class 2'),
  ALTER COLUMN s1            SET OPTIONS(description='number of papers with static RCI class 1'),
  ALTER COLUMN s0            SET OPTIONS(description='number of papers with static RCI class 0 (uncited)');

END;`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
