/*
## Summary
(NOT YET IMPLEMENTED) Create a summary report for all Australian HEPs.

## Description

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires

## Creates
*/
const compile = ({
  ns_core   = 'project.dataset',
  ns_inst   = 'project.dataset',
  replace   = false,
}) => `
-- generated by: ${__filename}
-- NOT YET IMPLEMENTED
`;
const compile_all = (args={}) => [ compile(args) ];
module.exports = { compile, compile_all };
if (require.main === module) require('app').cli_compile(compile_all);
