/*
## Summary
Build or rebuild analysis tables for a specific topic of research.

## Description
Builds a set of tables that focus on analysis for a single topic of research, defined by a topic ID.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0
*/
function compile_report_heps(conf={}) {
  console.log('NOT IMPLEMENTED YET');
  return [];

  const report_topic = require('../queries/report_topic').compile;
  const queries = [`
    -------------------------------------------------------------------------------
    -- WARNING: these queries are machine-generated. Any changes that you make   --
    -- here will be overwritten on the next compilation. If a permanent query    --
    -- alteration is required then modify the files in /code/queries/            --
    -------------------------------------------------------------------------------
    -- generated by: ${__filename}
    CREATE SCHEMA IF NOT EXISTS \`${conf.ns_core}\`;
  `];
  queries.push(report_topic(conf));
  return queries;
}
module.exports = compile_report_heps;
if (require.main === module) require('app').cli_compile(module.exports);
