/*
## Summary
Run SQL queries to (re)build the foundational data tables

## Description
This script will build the series of core_* tables in the database that you link to. It requires 
that the raw_* series of tables have first been constructed by compile_raw.js

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0
*/
function compile_core(conf={}) {
  return [`
    -------------------------------------------------------------------------------
    -- WARNING: these queries are machine-generated. Any changes that you make   --
    -- here will be overwritten on the next compilation. If a permanent query    --
    -- alteration is required then modify the files in /code/queries/            --
    -------------------------------------------------------------------------------
    -- generated by: ${__filename}
    CREATE SCHEMA IF NOT EXISTS \`${conf.ns_core}\`;
    `,
    require('../queries/core_rors'    ).compile(conf),
    require('../queries/core_heps'    ).compile(conf),
    require('../queries/core_fors'    ).compile(conf),
    require('../queries/core_journals').compile(conf),
    require('../queries/core_papers'  ).compile(conf),
    require('../queries/core_outputs' ).compile(conf),
  ];
}
module.exports = compile_core;
if (require.main === module) require('app').cli_compile(module.exports);
